# Generated by Django 4.2.10 on 2024-02-29 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=50)),
                ('published_date', models.DateField(default='')),
                ('isbn', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_date', models.DateField(default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_library.book')),
                ('rented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
